---
# This is the main tasks file for role1

- name: Ensure apache is at the latest version
  yum:
    name: httpd
    state: latest

- name: Write the apache config file
  template:
    src: /srv/httpd.j2
    dest: /etc/httpd.conf

- name: Ensure apache is running
  service:
    name: httpd
    state: started